- name: 1. Instalar MariaDB server
  apt: name=mariadb-server state=present

- name: 2. Iniciar servicio MySQL
  service: name=mysql state=started enabled=true

- name: 3. Instalar python Mysql #required for mysql_db tasks
  apt: name=python-mysqldb state=present

- name: 4. Instalar dependencias de MySQL
  apt: name=libmysqlclient-dev state=present

- name: 5. Crear una base de datos nueva
  mysql_db: name=demo state=present collation=utf8_general_ci

- name: 4. Crear un usuario en la base de datos
  mysql_user: name=demo password=demo priv=*.*:ALL host=localhost state=present

- name: 5a. Copiar datos de ejemplo
  copy: src=dump.sql dest=/tmp/dump.sql

- name: 5b. Insertar los datos de ejemplo
  shell: cat /tmp/dump.sql | mysql -u demo -pdemo demo

- name: 6a. Instalar la extensión de PHP para MySQL
  apt: name=php-mysql state=present

- name: 6b. Reiniciar Apache
  service: name=apache2 state=restarted

- name: 7. Instalar el script de Hello World con conexión a base de datos
  copy: src=db.php dest=/var/www/html/db.php mode=0664
